name: beauty4u-vue

on:
  push:
    branches:
      - "develop"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Generate Environment Variables File for Production
        run: |
          echo "VITE_APP_TITLE=$VITE_APP_TITLE" >> .env.staging
          echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" >> .env.staging
          echo "VITE_API_CHAT_URL=$VITE_API_CHAT_URL" >> .env.staging

        env:
          VITE_APP_TITLE: ${{ secrets.VITE_APP_TITLE }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_API_CHAT_URL: ${{ secrets.VITE_API_CHAT_URL }}

      - name: Debug .env.staging
        run: cat .env.staging

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --mode staging

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Sync with S3
        run: |
          aws s3 sync dist/ s3://beauty4u-vue --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/*"